[project]
name = "eqcli"
version = "0.3.1"
description = "In-house tools for equity reports at DataHaven"
readme = "README.md"
authors = [
    { name = "camille-s", email = "camille@ctdatahaven.org" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "pandas>=3.0.0",
    "pyyaml>=6.0.3",
    "tabulate>=0.9.0",
]

[project.scripts]
eqcli = "eqcli:cli.cli"

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[tool.uv]
package   = true

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-click>=0.9.0",
    "mkdocstrings[python]>=1.0.3",
    "pre-commit>=4.5.1",
    "pymdown-extensions>=10.21",
    "ruff>=0.15.1",
]
